### PR TITLE
:bug: input / fields not applying prop 'disabled'

### PR DESCRIPTION
**Pull request by AFaugeras**
Disabled fields didn't give the prop `disabled` to the input tag

### CODE REVIEW

**Comment by fabienjuif** [comment]
This is boring that the circle doesn't trigger on forks ...

**Comment by fabienjuif** [comment]
Can you push a dummy commit right now to test the new circle ci configuration ?

**Comment by AFaugeras** [comment]
Ok, the integration of circle seams to be working. It just reminds me that I forgot to refresh the tests...

**Comment by fabienjuif** [comment]
rhaa coveralls...

**Comment by AFaugeras** [comment]
Err, that's what I was just checking, didn't see that :(

**Comment by fabienjuif** [comment]
This is about our circle configuration I guess. 
I'll look manually coverage and we could merge

**Comment by fabienjuif** [comment]
Ok seem fine to me, can you build the lib (`yarn build`) then push a new commit with it ?

**Comment by fabienjuif** [comment]
Is it ok we wait #98 to publish both PR in a new version ?

**Comment by fabienjuif** [comment]
Thank you @AFaugeras :)

**Comment by AFaugeras** [comment]
You're welcome ;)

**Pull request merged**
